# Generated by Django 5.1.1 on 2024-11-14 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(blank=True, max_length=20)),
                ('member_name', models.CharField(max_length=20)),
                ('member_info', models.CharField(blank=True, max_length=128)),
                ('member_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=20)),
                ('group_name', models.CharField(max_length=32)),
                ('group_members', models.ManyToManyField(blank=True, related_name='groups', to='users.member')),
            ],
        ),
    ]
