# Generated by Django 5.1.1 on 2024-11-14 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join', to='users.member')),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='group_members',
            field=models.ManyToManyField(blank=True, related_name='groups', to='users.joining'),
        ),
    ]
