# Generated by Django 5.1.3 on 2024-11-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joining',
            name='joined_rank',
            field=models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=10),
        ),
    ]
