# Generated by Django 5.1.3 on 2024-11-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_joining_joined_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joining',
            name='joined_rank',
            field=models.CharField(choices=[('owner', 'Owner'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=10),
        ),
    ]
