# Generated by Django 5.1.3 on 2024-11-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='importance',
            field=models.CharField(choices=[('1', 'Very Important'), ('2', 'Important'), ('3', 'Normal')], default='3', max_length=10),
        ),
    ]
