# Generated by Django 5.1.3 on 2024-12-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime'),
        ),
        migrations.AddField(
            model_name='event',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
